stages:
  train:
    cmd: python src/train.py
    deps:
    - src/train.py
    - data/train.csv
    - data/test.csv
    outs:
    - models/model.pkl
    - models/vectorizer.pkl
    - metrics/accuracy.json
