stages:
  prepare:
    cmd: python src/prepare_data.py
    deps:
      - src/prepare_data.py
      - data/IMDB Dataset.csv
    outs:
      - data/train.csv
      - data/test.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/train.csv
      - data/test.csv
    outs:
      - models/model.pkl
      - models/vectorizer.pkl
      - metrics/accuracy.json
