name: CI - Train & Test

on: [push, pull_request]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run prepare + train
        run: |
          python src/prepare_data.py
          python src/train.py
      - name: Save metrics
        run: cat metrics/accuracy.json
