name: IMDB Sentiment CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:           # manual trigger
  repository_dispatch:         # external trigger from Dagshub webhook

jobs:
  build-train-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      # ------------------------
      # Checkout repo
      # ------------------------
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # required for pushing back changes

      # ------------------------
      # Setup Python
      # ------------------------
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # ------------------------
      # Install dependencies
      # ------------------------
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc[s3]  # adjust depending on your Dagshub remote type

      # ------------------------
      # Configure DVC remote (Dagshub)
      # ------------------------
      - name: Configure DVC remote
        run: |
          dvc remote modify dagshub --local auth basic
          dvc remote modify dagshub --local user Dharsh
          dvc remote modify dagshub --local password 4f3284cea30d20043975370eef81965d94e13fe1

      # ------------------------
      # Clean local DVC cache and outputs
      # ------------------------
      - name: Clean DVC cache and outputs
        run: |
          rm -rf .dvc/cache
          rm -rf data/processed/* || true
          rm -rf artifacts/* || true
          rm -rf models/* || true

      # ------------------------
      # Pull all DVC outputs fresh
      # ------------------------
      - name: Pull DVC outputs
        run: dvc pull -r dagshub --force

      # ------------------------
      # Reproduce pipeline (train if needed)
      # ------------------------
      - name: Reproduce DVC pipeline
        run: dvc repro

      # ------------------------
      # Push updated outputs to Dagshub
      # ------------------------
      - name: Push updated outputs to Dagshub
        run: dvc push -r dagshub

      # ------------------------
      # Commit & push repo changes (like dvc.lock updates)
      # ------------------------
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "Update pipeline outputs [skip ci]"
          git push origin HEAD:main

      # ------------------------
      # Verify pulled files
      # ------------------------
      - name: Verify files
        run: |
          echo "Data files:"
          ls -l data/processed/ || echo "No processed data"
          echo "Artifacts:"
          ls -l artifacts/ || echo "No artifacts"
          echo "Models:"
          ls -l models/ || echo "No models"

      # ------------------------
      # Upload artifacts (model + metrics)
      # ------------------------
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: imdb-sentiment-artifacts
          path: |
            artifacts/
            models/

      # ------------------------
      # Test API import
      # ------------------------
      - name: Test API import
        run: python -c "from src import app; print('App imported successfully')"
